'built footer'
rileydanejohnston/apiary-acc pull request #9
Opened 2022-03-09 03:21 UTC by Trisboyd

The organization of the elements is kind of a mess, but the design left me little choice.  Each block is slightly different but instead of creating separate blocks I matched them as much as I could and passed in several props to create differences.

One thing I did fudge (which we can change if we want) is the margin underneath each block title is different and I evened them out to the relative average.  This seems more consistent to me, but I'm open to disagreement.

2022-03-09 23:07 UTC, rileydanejohnston requested changes
Overall, looks great! I few small changes per the new design and we are ready.

2022-03-09 23:07 UTC, rileydanejohnston commented on src/constants/footer.js
> +            text1: 'hello@acc.com',
email is Hello@AwesomeContainers.com per final design (it says Hello@AwesomeContaners.com, I assume it should be 'containers')

2022-03-09 23:07 UTC, rileydanejohnston commented on src/constants/footer.js
> +            text2: '+65 0123 4567',
phone number has been removed

2022-03-09 23:07 UTC, rileydanejohnston commented on src/constants/footer.js
> +            text3: 'Blk 35 Mandalay Road # 13-37',
address has changed to 'Address: 71 UBI Road 1, #08-42,  Oxley Bizhub, Singapore 408732'

2022-03-09 23:07 UTC, rileydanejohnston commented on src/constants/footer.js
> +            link2: 'twitter',
twitter has been removed

2022-03-09 23:07 UTC, rileydanejohnston commented on src/constants/footer.js
> +            link1: 'instagram',
it says 'AwesomeContainers' instead of instagram now

2022-03-09 23:07 UTC, rileydanejohnston commented on src/constants/footer.js
> +        'Awesome Container Compnay © 2022',
'Company' is misspelled, i see it's spelled this way on the design but we should fix it

2022-03-09 23:07 UTC, rileydanejohnston commented on src/components/footer/Footer.js
> +import { Block, BlockText, BlockTitle, FooterBlocks, FooterBottom, FooterWrapper, ImgBackground, Link, LinkImg, LinkWrapper, TextBlock, TextLine, TextLineS, TextWrapper } from "./styledFooter"
we should remove the things we are not using like 'BlockText' in both this import statement and in styledFooter.js

2022-03-09 23:07 UTC, rileydanejohnston commented on src/components/footer/Footer.js
> +    links
links isn't used

2022-03-09 23:07 UTC, rileydanejohnston commented on src/components/footer/Footer.js
> +                    Awesome Container Compnay © 2022
Company > compnay

2022-03-09 23:07 UTC, rileydanejohnston commented on src/components/footer/Footer.js
> +                            <Block key={blocks.indexOf(data)}>
key property is not necessary. We only need it when we use map with a ul element. My bad on this again

2022-03-11 02:49 UTC, rileydanejohnston commented on src/constants/footer.js
> +        'Awesome Container Company © 2022',
Is this ever used? I notice the HTML still has this as well, but company is misspelled in the HTML

2022-03-11 02:56 UTC, rileydanejohnston requested changes
I think it's close. A few more changes and it will be ready

2022-03-11 02:56 UTC, rileydanejohnston commented on src/components/footer/Footer.js
> +                    Awesome Container Compnay © 2022
I recommend either putting the text in the HTML or in the const file. Right now there's both.

2022-03-11 02:56 UTC, rileydanejohnston commented on src/components/footer/Footer.js
> +                        <Block key={blocks.indexOf(data)}>
Key is unnecessary

2022-03-11 02:56 UTC, rileydanejohnston commented on src/components/footer/styledFooter.js
> +export const LinkWrapper = styled.div`
the text should be aligned in the middle of the image, try adding 'align-items: center;'. I think that will do the trick

2022-03-11 03:30 UTC, Trisboyd commented
I don't know how I missed that the name is placed in the constants and hardcoded AND misspelled.  I missed that TWICE even though you told me the second time.  Thanks for being observant.

2022-03-11 04:40 UTC, rileydanejohnston approved these changes

2022-03-11 22:47 UTC, merged